Controllers/DamageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GoA_Site.Models;

namespace GoA_Site.Controllers
{
    public class DamageController : Controller
    {
        private readonly Fire FS = new Fire();

   
        public async Task<ActionResult> Index()
        {

            IEnumerable<Damage> x = await FS.GetGuildDDs();
            
            
            return View(x);
        }

        // GET: Damage/Details/5
        public async Task<ActionResult> Details(String id)
        {

            var Guildie = await FS.GetGuildDamage(id);
            return View(Guildie);
           
        }

        // GET: Damage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Damage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {

            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);
            string type = Convert.ToString(collection["Type"]);
            string clas = Convert.ToString(collection["Class"]);
            Double dps = Convert.ToDouble(collection["DPS"]);
            string parse = Convert.ToString(collection["Parse"]);
            try
            {
                var newDamage = new Damage(ign, name, dps, type, clas, parse);
                await FS.AddNewDD(newDamage);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                var y = e;
                return View();
            }
        }

        // GET: Damage/Edit/5
        public async Task<ActionResult> Edit(String id)
        {
            var Guildie = await FS.GetGuildDamage(id);
            return View(Guildie);
        }

        // POST: Damage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);
            string type = Convert.ToString(collection["Type"]);
            string clas = Convert.ToString(collection["Class"]);
            Double dps = Convert.ToDouble(collection["DPS"]);
            string parse = Convert.ToString(collection["Parse"]);
            try
            {
                var newDamage = new Damage(ign, name, dps, type, clas, parse);
                await FS.AddNewDD(newDamage);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Damage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Damage/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HealerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GoA_Site.Models;

namespace GoA_Site.Controllers
{
    public class HealerController : Controller
    {
        private readonly Fire FS = new Fire();

   
        public async Task<ActionResult> Index()
        {

            IEnumerable<Healer> x = await FS.GetGuildDDs();
            
            
            return View(x);
        }

        // GET: Healer/Details/5
        public async Task<ActionResult> Details(String id)
        {

            var Guildie = await FS.GetGuildHealer(id);
            return View(Guildie);
           
        }

        // GET: Healer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Healer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {

            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);
            string type = Convert.ToString(collection["Type"]);
            string clas = Convert.ToString(collection["Class"]);
            Double dps = Convert.ToDouble(collection["DPS"]);
            string parse = Convert.ToString(collection["Parse"]);
            try
            {
                var newHealer = new Healer(ign, name, dps, type, clas, parse);
                await FS.AddNewDD(newHealer);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                var y = e;
                return View();
            }
        }

        // GET: Healer/Edit/5
        public async Task<ActionResult> Edit(String id)
        {
            var Guildie = await FS.GetGuildHealer(id);
            return View(Guildie);
        }

        // POST: Healer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);  
            string clas = Convert.ToString(collection["Class"]);
            try
            {
                var newHealer = new Healer(ign,name,clas);
                await FS.AddNewDD(newHealer);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Healer/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var Guildie = await FS.GetGuildHealer(id);
            return View(Guildie);
        }

        // POST: Healer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(String id, IFormCollection collection)
        {
            try
            {
                await FS.DeleteGuildHealer(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GoA_Site.Models;

namespace GoA_Site.Controllers
{
    public class TankController : Controller
    {
        private readonly Fire FS = new Fire();

   
        public async Task<ActionResult> Index()
        {

            IEnumerable<Tank> x = await FS.GetGuildTanks();
            
            
            return View(x);
        }

        // GET: Tank/Details/5
        public async Task<ActionResult> Details(String id)
        {

            var Guildie = await FS.GetGuildTank(id);
            return View(Guildie);
           
        }

        // GET: Tank/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tank/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {

            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);
            string clas = Convert.ToString(collection["Class"]);
           
        
            try
            {
                var newTank = new Tank(ign,name,clas);
                var TankGear = new TankGear(ign);
                await FS.AddNewTank(newTank);
                await FS.AddNewTankGear(TankGear);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                var y = e;
                return View();
            }
        }

        // GET: Tank/Edit/5
        public async Task<ActionResult> Edit(String id)
        {
            var Guildie = await FS.GetGuildTank(id);
            return View(Guildie);
        }

        // POST: Tank/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            string ign = Convert.ToString(collection["InGameName"]);
            string name = Convert.ToString(collection["CharacterName"]);  
            string clas = Convert.ToString(collection["Class"]);
            try
            {
                var newTank = new Tank(ign,name,clas);
                await FS.AddNewTank(newTank);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Tank/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var Guildie = await FS.GetGuildTank(id);
            return View(Guildie);
        }

        // POST: Tank/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(String id, IFormCollection collection)
        {
            try
            {
                await FS.DeleteGuildTank(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TankGearController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoA_Site.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GoA_Site.Controllers
{
    
    public class TankGearController : Controller
    {
        private readonly Fire FS = new Fire();
        // GET: TankGear
        public async Task<ActionResult> Index()
        {
            IEnumerable<TankGear> x = await FS.GetAllTankGear();
            return View(x);
        }

        // GET: TankGear/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var x = await FS.GetTankGear(id);
            return View(x);
        }

      

        // GET: TankGear/Edit/5
        public async Task<ActionResult> Edit(String id)
        {
            var x = await FS.GetTankGear(id);
            return View(x);

        }

        // POST: TankGear/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: TankGear/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManagementSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
            <a class="navbar-brand" href="#">ThAmCo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Staff
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link text-dark" asp-controller="GuildMember" asp-action="Index">View Guild Members</a>
                            <a class="nav-link text-dark" asp-controller="GuildMember" asp-action="Create">Add New Guild Member</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            DD
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link text-dark" asp-controller="Damage" asp-action="Index">DD Roster</a>
                            <a class="nav-link text-dark" asp-controller="Damage" asp-action="Create">Add DD</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Healer
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="nav-link text-dark" asp-controller="Healer" asp-action="Index">Healer Roster</a>
                            <a class="nav-link text-dark" asp-controller="Healer" asp-action="Create">Add Healer</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tank
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="nav-link text-dark" asp-controller="Tank" asp-action="Index">Tank Roster</a>
                            <a class="nav-link text-dark" asp-controller="Tank" asp-action="Create">Add Tank</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tank Gear
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="nav-link text-dark" asp-controller="TankGear" asp-action="Index">All Tank Gear</a>
                        </div>
                    </li>
                </ul>
           
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>